# 1. Site settings
theme: jekyll-theme-minimal
logo: "/assets/logos/logo.jpg"
title: "Danishjeet Singh"
author: "Danishjeet Singh"
email: "singhdan@iu.edu"
# google_analytics: "UA-167616887-1"

# 2. Collection
collections:
  posts:
    output: true

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/danishjeetsingh
  GitHub: https://github.com/danishjeetsingh

sass:
  style: compressed
  
keep_files: [assets]
# Exclude from processing
exclude:
  - assets/css/style.css
  - assets/css/pygment_trac.css

